before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng"
script:
- pdflatex weighbh.tex
- bibtex weighbh
- pdflatex weighbh.tex
- pdflatex weighbh.tex
deploy:
  provider: releases
  api_key:
    secure: "MIIEpAIBAAKCAQEA7EKQvyljgWewK0A7tB7EIhW3vPM3YTtA7m8a4keyJTWHDSI1
1kfKvkUnP3oph/NzPWab3xlOZeb4FG+wc+LiPCL5i2nHJMj+bJ2VL3xpwg6OvvvZ
UOfPrKnzc+DWok75k3/iJm0JoH1NCGovTY0c2KXviQylDYtefOpoimbf8D1mu/LM
rSptsHmzrOAuqZI5apR5oeOrlWUGyCuwEn9S5BGwxSoKQHdUZ2eZRqjba1/VBEJO
paDYqU6wYAVRPJzgXolqt1epvvlSy31P57kdvCAQTM35V1cU2yMGDygYoXOQ9D2N
W4V+h8coukBCaM5As85GKHs+V+8jDWiCNy4S5wIDAQABAoIBAQCqDBcmn+GQyFKS
Lr9KG0LLzZnbk6rufrlzY+CTsUrVYTt9Bnx9aFrSq+9dzs2Jnn35WZsi7pHw4lb4
TpNQNaLj6cB2yYGeRlRpVNqFvSRZmiS/7YEyrEZbXk9tvgx98h3MPiVFxwFA1C7X
uaWmScTTYkuP9tvtbbxqaEUqKHVR8V18gdedZaT6Z0/ba6PjfJqxIF28QPg5+Yfs
RZJsQi8CJCTpiWKA8UI0EBZK4Ea3nKNDZW5Tc21DB0h2Gf5OxzeFQTR0N4z6vDWI
ec1Ls+9mSVrlfk/y3HayMH20girpYY2NHn84kOHy5SJSPjXMmP9Fjju5fv9uPCpm
G82+oiTBAoGBAP65IO2wK+DnSz7O5ZewQuI2NrSVEHfXTepPIK59rrEiVag5mJRC
wt1Hc/ZcBAFuFb00XXL+tSf5Y5ysDoTVDGMPHurRqUxmgsHXyrXyOjiaVv2Ln2IX
0edmHVw5vJAv4CkVU4wEXq8j254Ntt4WaeNklsWhD0wgzA8uUPv7pan3AoGBAO1x
vn7P2ub2rm2O4so2DyATpUB4vDXBnofd7RZ6E9A+hVJbRos9+ZGc9bJg+Z2Kx4r8
y3BJbC4g5fejD7T8zbTZcmn8QhX/kgPzPApejyYdpVWUjZzlmbouKI+Mwv1bvsOL
AngXmUnJBcUjkAudm8FGaqbV4kZ7XqSUiwa+6iKRAoGBAKDy1Q2a3X7UZsUe8g9w
vjI1U0ezUJ6ImqDMsrfOjk06hqkvC2vS61HqTimCZr2Ik4/jwJBixJCnkfty9BGW
lKca7MwvAixWMZTOBzYEAim1y/WU/XZ72pO+ABtAGBd7SMZsxUeZk0JTA/fQbpXR
z8Jw0pu5cvMFXirRdzZhAYJtAoGAa0da1BzBQFzvzhwip03pY4q8vPZPwtHp+GTy
e5dIYGv+/Ii0xLCJk5qg/6kE3oMXSNqSZ/ckY2sFu+72Z8VYg39DTFNm4F2J8TLy
S5URhB0c2B+4I80wuYelV8Y3SxUqiVrDENNItKeYbct1h2n8N0TDZwF3rHSM/DsI
3VFgo6ECgYBUVpwP4QnsCox/nuW/baR38mHDZQpQuwVdpwbeKEJVJngyR3P1CJmt
gdpp/N4u3wqwJE4NyD/vbS2DUMs62mpzFhMSb39qDA8WSNVqHT72hGjp9hgDYJoi
8i/8d42VZMIGjZa0QuhPF8PEvZvygrc4Xn5YJzBgi7iubcNLm8yQ1A=="
  file:
  - weighbh.pdf
  skip_cleanup: true
  on:
    tags: true
