before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng"
script:
- pdflatex weighbh.tex
- bibtex weighbh
- pdflatex weighbh.tex
- pdflatex weighbh.tex
deploy:
  provider: releases
  file:
  - weighbh.pdf
  skip_cleanup: true
  on:
    tags: true
