before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng"
script:
- mkdir _build
- pdflatex -output-directory _build weighbh.tex
deploy:
  provider: releases
  file:
  - _build/your_file_1.pdf
  - _build/your_file_2.pdf
  skip_cleanup: true
  on:
    tags: true
