before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng"
script:
- mkdir _build
- pdflatex -output-directory _build weighbh.tex
- bibtex weighbh.tex
- pdflatex -output-directory _build weighbh.tex
- pdflatex -output-directory _build weighbh.tex
deploy:
  provider: releases
  file:
  - _build/weighbh.pdf
  skip_cleanup: true
